name: reviewdog
on: [pull_request, push]

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    with:
      fail_on_error: true
    steps:
      - uses: actions/checkout@v4
      - uses: errata-ai/vale-action@v2.1.1
        with:
           fail_on_error: true
           filter_mode: file
           reporter: github-check
           level: warning
